### ISSUE TITLE
[object Object] inserted in mail body instead of configured responses text

### ISSUE THREAD

**Issue by magnific0** [random-cuber/responses#4]
I just installed the responses plugin for the first time on my system. I have successfully enabled the plugin and configured a new response. All options under "Composing Messages" are enabled.

However when I select a response, for example "[plugin.responses] text thank you", only:

    [object Object]

is inserted in the message body. The subject line however is correctly replaced, becoming: [YES] original subject text.

My versions are as follows.

- reponses latest as of writing: f1f0c8d30506bd8ed7fd1982c8bb7f754e73efb7
- roundcube: 1.1.3
- other enabled plugins: archive, zipdownload, acl, managesieve, password, persistent_login, attachment_reminder, new_user_dialog
- PHP 5.6

Do you have any idea what might be causing this? The plugin looks really promising and I'd like to use!

**Comment by magnific0** [comment]
My apologies. The issue was solved by upgrading to roundcube version 1.3.3. Closing this myself.

**Comment by Andrei-Pozolotin** [comment]
thank you
